name: 'Rudder Transformer Test and Publish'
description: 'Test user transformations'
inputs:
    metaPath:
        description: 'File containing transformation and libraries meta'
        required: true
    email:
        description: 'email'
        required: true
    accessToken:
        description: 'token'
        required: true
    serverEndpoint:
        description: 'backend url'
        required: true
        default: 'https://api.rudderlabs.com'
    uploadTestArtifact:
        description: 'upload test results'
        required: false
runs:
    using: 'node12'
    main: 'dist/index.js'