name: Publish Transformations

on:
  pull_request:
    branches: ['main']

jobs:
  publish:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.setenv.outputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Set environment
        id: setenv
        run: |
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          else
            echo "environment=development" >> $GITHUB_OUTPUT
          fi
      - name: Deploy/Publish
        env:
          ENVIRONMENT: ${{ steps.setenv.outputs.environment }}
        uses: rudderlabs/rudder-transformation-action@v1.1.4
        with:
          metaPath: './meta.json'
          email: ${{ github.event.pusher.email }}
          accessToken: ${{ secrets.SERVICE_ACCESS_TOKEN }}
          uploadTestArtifact: true