name: Rudder Transformer Test and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rudderlabs/rudder-transformation-action@v1.1.4
        with:
          metaPath: './code/meta.json'
          email: ${{ github.event.pusher.email }}
          accessToken: ${{ secrets.ACCESS_TOKEN }}
          uploadTestArtifact: true
