name: Publish Transformations

on:
  push:
    branches:
      - main
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set environment
        id: setenv
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi
      - name: Deploy/Publish
        env:
          ENVIRONMENT: ${{ steps.setenv.outputs.environment }}
        uses: rudderlabs/rudder-transformation-action@v1.1.4
        with:
          metaPath: './meta.json'
          email: ${{ github.event.pusher.email }}
          accessToken: ${{ secrets.SERVICE_ACCESS_TOKEN }}
          uploadTestArtifact: true
