name: Publish Transformations

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set environment
        id: setenv
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          else
            echo "environment=prod" >> $GITHUB_OUTPUT
          fi
      - name: Deploy/Publish
        env:
          ENVIRONMENT: ${{ steps.setenv.outputs.environment }}
        uses: AlexKnusel-MKETool/rudder-transformation-action@ui-repo-linking
        with:
          metaPath: './meta.json'
          email: ${{ github.event.pusher.email || github.actor }}
          accessToken: ${{ steps.setenv.outputs.environment == 'prod' && secrets.SERVICE_ACCESS_TOKEN_PROD || secrets.SERVICE_ACCESS_TOKEN_DEV }}
          uploadTestArtifact: true
