name: Test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  request:
    runs-on: ubuntu-latest
    env:
      TEST_ONLY: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Rudder Transformer Test and Publish
        uses: ./
        with:
          metaPath: './code/meta.json'
          email: 'jayachand+88@rudderstack.com'
          accessKey: '1segPLUELpRwFmioa1h8OraXhVO'
          serverEndpoint: 'https://aa88e07d9346.ngrok.io'
          uploadTestArtifact: true