name: Test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Rudder Transformer Test and Publish
        uses: ./
        with:
          metaPath: './code/meta.json'
          email: 'test1619427853838@rudderlabs.com'
          accessKey: '1rhrWotHszP3eVma57BzAP67QWA'
          serverEndpoint: 'https://aa88e07d9346.ngrok.io'
          uploadTestArtifact: true